{% set version = "5.1.0" %}

package:
  name: ipyparallel
  version: {{ version }}

source:
  fn: ipyparallel-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/i/ipyparallel/ipyparallel-{{ version }}.tar.gz
  sha256: f217fdf9fc38d60ae4a4dc07cfc2ce27568cf156a3cd891137a00c4c5c4048c5

build:
  number: 0
  script: pip install --no-deps .

requirements:
  build:
    - python
    - futures               # [py<32]
    - decorator
    - tornado >=4
    - pyzmq >=13
    - ipython_genutils
    - ipython >=4
    - jupyter_client
    - ipykernel
    - tornado >=4

  run:
    - python
    - futures               # [py<32]
    - decorator
    - tornado >=4
    - pyzmq >=13
    - ipython_genutils
    - ipython >=4
    - jupyter_client
    - ipykernel

test:
  imports:
    - ipyparallel
    - ipyparallel.apps
    - ipyparallel.client
    - ipyparallel.controller
    - ipyparallel.engine
    - ipyparallel.serialize

about:
  home: http://ipython.org
  license: BSD 3-Clause
  summary: Interactive Parallel Computing with IPython

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
