{% set name = "ipyparallel" %}
{% set version = "9.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d992edd698a99d45f2d9059af1c9ae8f086d1aeedb3e80436029a2f28d069f83

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation --ignore-installed .
  entry_points:
    - ipcluster = ipyparallel.cluster.app:main
    - ipcontroller = ipyparallel.controller.app:main
    - ipengine = ipyparallel.engine.app:main
  skip: true # [py<38]

requirements:
  host:
    - python
    - pip
    - hatchling >=0.25
    - jupyterlab ==4.*
  run:
    - python
    - decorator
    - pyzmq >=25
    - traitlets >=5
    - ipython >=5
    - jupyter_client >=7
    - ipykernel >=6.9.1
    - tornado >=6.1
    - psutil
    - python-dateutil >=2.1
    - tqdm

test:
  imports:
    - ipyparallel
    - ipyparallel.apps
    - ipyparallel.client
    - ipyparallel.controller
    - ipyparallel.engine
    - ipyparallel.serialize
  commands:
    - pip check
    - ipcluster -h
    - ipcontroller -h
    - ipengine -h
    - jupyter labextension list
    - jupyter server extension list
    - jupyter nbclassic extension list
    - jupyter labextension list 1>labextensions 2>&1
    - jupyter server extension list 1>server_extensions 2>&1
    - jupyter nbclassic extension list 1>nbclassic_extensions 2>&1
    - python -c "import re, pathlib; assert re.findall('ipyparallel-labextension.*OK', pathlib.Path('labextensions').read_text())"
    - python -c "import re, pathlib; assert re.findall('ipyparallel.*OK', pathlib.Path('server_extensions').read_text())"
    - python -c "import re, pathlib; assert re.findall('ipyparallel.*OK', pathlib.Path('nbclassic_extensions').read_text())"
    - pytest --pyargs --asyncio-mode=auto ipyparallel.tests
  requires:
    - pip
    - pytest
    - pytest-asyncio
    - jupyterlab ==4.*
    - jupyter_server <3
    - notebook
    - nbclassic
    - m2-grep  # [win]

about:
  home: https://github.com/ipython/ipyparallel
  license: BSD-3-Clause
  license_file: COPYING.md
  license_family: BSD
  summary: Interactive Parallel Computing with IPython
  description: |
    IPython Parallel (ipyparallel) is a Python package and collection of CLI scripts 
    for controlling clusters of IPython processes, built on the Jupyter protocol.
  doc_url: https://ipyparallel.readthedocs.io
  dev_url: https://github.com/ipython/ipyparallel

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
