{% set version = "5.1.1" %}

package:
  name: ipyparallel
  version: {{ version }}

source:
  fn: ipyparallel-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/i/ipyparallel/ipyparallel-{{ version }}.tar.gz
  sha256: c46cd3bad50bbe12106257241d671ce6edb3faca2ced54ed001b8f1d579720f0

build:
  number: 0
  script: pip install --no-deps .

requirements:
  build:
    - python
    - futures               # [py<32]
    - decorator
    - tornado >=4
    - pyzmq >=13
    - ipython_genutils
    - ipython >=4
    - jupyter_client
    - ipykernel
    - tornado >=4

  run:
    - python
    - futures               # [py<32]
    - decorator
    - tornado >=4
    - pyzmq >=13
    - ipython_genutils
    - ipython >=4
    - jupyter_client
    - ipykernel

test:
  imports:
    - ipyparallel
    - ipyparallel.apps
    - ipyparallel.client
    - ipyparallel.controller
    - ipyparallel.engine
    - ipyparallel.serialize

about:
  home: http://ipython.org
  license: BSD 3-Clause
  summary: Interactive Parallel Computing with IPython

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
