{% set version = "6.0.1" %}
{% set sha256 = '968da8dbf0d3cad97d588994da6739851ec7ae9e98f851a333adb4eff3d930f0' %}
{% set build = 0 %}

package:
  name: ipyparallel
  version: {{ version }}

source:
  fn: ipyparallel-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/i/ipyparallel/ipyparallel-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  script:
    - pip install --no-deps .
    - jupyter nbextension install --sys-prefix --py ipyparallel

requirements:
  build:
    - python
    - pip
    - futures               # [py<32]
    - decorator
    - tornado >=4
    - python-dateutil >=2.1
    - pyzmq >=13
    - ipython_genutils
    - ipython >=4
    - jupyter_client
    - ipykernel
    - tornado >=4
    # To install the notebook extension.
    #
    # We don't require this to install/use
    # ipyparallel though. So we don't make
    # it a run-time requirement.
    - notebook

  run:
    - python
    - futures               # [py<32]
    - decorator
    - tornado >=4
    - python-dateutil >=2.1
    - pyzmq >=13
    - ipython_genutils
    - ipython >=4
    - jupyter_client
    - ipykernel

test:
  imports:
    - ipyparallel
    - ipyparallel.apps
    - ipyparallel.client
    - ipyparallel.controller
    - ipyparallel.engine
    - ipyparallel.serialize

about:
  home: http://ipython.org
  license: BSD 3-Clause
  summary: Interactive Parallel Computing with IPython

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
