{% set version = "6.1.1" %}
{% set sha256 = 'f1e03ebb8d17f67f03bafa5d85f220883462f7bd7a97fe904c7d56ffba8534a3' %}
{% set build = 1 %}

package:
  name: ipyparallel
  version: {{ version }}

source:
  fn: ipyparallel-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/i/ipyparallel/ipyparallel-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}

requirements:
  build:
    - python
    - pip
    - notebook

  run:
    - python
    - futures               # [py2k]
    - decorator
    - tornado >=4
    - python-dateutil >=2.1
    - pyzmq >=13
    - ipython_genutils
    - ipython >=4
    - jupyter_client
    - ipykernel

test:
  requires:
    - notebook >=5.3
  imports:
    - ipyparallel
    - ipyparallel.apps
    - ipyparallel.client
    - ipyparallel.controller
    - ipyparallel.engine
    - ipyparallel.serialize
  commands:
    - ipcluster -h
    - ipengine -h
    - ipcontroller -h

about:
  home: http://ipython.org
  license: BSD 3-Clause
  summary: Interactive Parallel Computing with IPython

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
