travis:
  secure:
    BINSTAR_TOKEN: vTmXTVzSmrrIPTDKTeJN9ZD/bWftbqMn931eaaSwjTYg+8WGflva59kQQke1DLA8L/lOZsaJvWKGTOl+ij/wLY47S29/VkOaE6FBVzpcUkFh8NDcC1iD4T5FHwBVDAaF7JraQGC3F/Hr1dja8runuO5fLbWlh654jm+9V3tot3ITOW3N2RhGaneJE/7le0YZiMYYzyRmki91Imzor2AsoeDqxdXAx00we4mqf08ZSbNIU2HqIsQ4j1LhdrM/9JXVkBUN9XGdvr131Yb1CNdQrEquyXrrP1XBZb47e59qkEC1AK5UeJdksk3VB0UpFUceXoHtuMJpbCfwR2cZG3AHFO920nAJX2QWf/l6VGzmX8KDC3AtIZQOmR/GJ+ipZg5kwkxesPvqtkEecEqDF5Ww3yqn12g+sW7a2t+1pJf994MU7BcYQL0CRcgGiEmybnkCI3T7Eogp4Au4Jz9b23BNfRlLfUMPDeLVjggEr2VLzfn9jTRBFBEYszKtSc3wTf58Ox6hNB7VEegEDMOOVVg5NoLSbzj7+KFPpQCw1moxgfHkTRu3NDwSaF/Jz0uRgwt27vDNNKo4wmptu14VRoyAajTEyc9+T+RZ4ptDMdhAC0qIOee8kZHvhUJeaKNCdu4MSSFac4YizLc01fvEOsWz5PoTyQVM9RmVuCIjSDETKbc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
